from __future__ import annotations

MARKET_TICKERS: dict[str, list[str]] = {
    "Suomi": [
        "VALMT.HE",
        "NOKIA.HE",
        "KNEBV.HE",
        "UPM.HE",
        "STERV.HE",
        "METSO.HE",
        "NESTE.HE",
        "FORTUM.HE",
        "WRT1V.HE",
        "KESKOB.HE",
    ],
    "Ruotsi": [
        "VOLV-B.ST",
        "ATCO-A.ST",
        "ERIC-B.ST",
        "HM-B.ST",
        "SEB-A.ST",
        "ABB.ST",
        "SWED-A.ST",
        "SAND.ST",
        "ALFA.ST",
        "TELIA.ST",
    ],
    "USA": [
        "AAPL",
        "MSFT",
        "NVDA",
        "TSLA",
        "META",
        "AMZN",
        "GOOGL",
        "AMD",
        "NFLX",
        "PYPL",
    ],
    "Saksa": [
        "SAP.DE",
        "SIE.DE",
        "ALV.DE",
        "BAS.DE",
        "BMW.DE",
        "MBG.DE",
        "DTE.DE",
        "IFX.DE",
        "VOW3.DE",
        "BAYN.DE",
    ],
}
